image: python:3

stages:
  - test

test-homework01:
  stage: test
  script:
    - cd homework01
    - pytest
  only:
    - homework01

test-homework02:
  stage: test
  script:
    - cd homework02
    - pytest
  only:
    - homework02

before_script:
  - pip install pytest numpy     
